// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpfwatcher

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadKillMonitor returns the embedded CollectionSpec for killMonitor.
func loadKillMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KillMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load killMonitor: %w", err)
	}

	return spec, err
}

// loadKillMonitorObjects loads killMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*killMonitorObjects
//	*killMonitorPrograms
//	*killMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKillMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadKillMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// killMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type killMonitorSpecs struct {
	killMonitorProgramSpecs
	killMonitorMapSpecs
	killMonitorVariableSpecs
}

// killMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type killMonitorProgramSpecs struct {
	TraceKill *ebpf.ProgramSpec `ebpf:"trace_kill"`
}

// killMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type killMonitorMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// killMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type killMonitorVariableSpecs struct {
}

// killMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKillMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type killMonitorObjects struct {
	killMonitorPrograms
	killMonitorMaps
	killMonitorVariables
}

func (o *killMonitorObjects) Close() error {
	return _KillMonitorClose(
		&o.killMonitorPrograms,
		&o.killMonitorMaps,
	)
}

// killMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKillMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type killMonitorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *killMonitorMaps) Close() error {
	return _KillMonitorClose(
		m.Events,
	)
}

// killMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKillMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type killMonitorVariables struct {
}

// killMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKillMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type killMonitorPrograms struct {
	TraceKill *ebpf.Program `ebpf:"trace_kill"`
}

func (p *killMonitorPrograms) Close() error {
	return _KillMonitorClose(
		p.TraceKill,
	)
}

func _KillMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed killmonitor_bpfel.o
var _KillMonitorBytes []byte
