syntax = "proto3";

package wartweets;

// Ruta propuesta del módulo Go; se creará en la fase 3.
option go_package = "github.com/vjr-velasquez/202100054_LAB_SO1_1S2026/proyecto3/services/go/gen/wartweets;wartweets";

message WarReportRequest {
  Countries country = 1;
  int32 warplanes_in_air = 2;
  int32 warships_in_water = 3;
  string timestamp = 4;
}

enum Countries {
  countries_unknown = 0;
  usa = 1;
  rus = 2;
  chn = 3;
  esp = 4;
  gtm = 5;
}

message WarReportResponse {
  string status = 1;
}

service WarReportService {
  rpc SendReport (WarReportRequest) returns (WarReportResponse);
}
